steps:
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        if [ ! -d "node_modules" ]; then
          echo "Menginstal Dependencies...."
          npm ci
        else
          echo "node_modules sudah ada !"
        fi
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
    - -c
    - |
      chmod +x node_modules/.bin/*
      npm run build
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm
  
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app","deploy","--quiet"]
    dir: "frontend"

options:
  logging: CLOUD_LOGGING_ONLY